version: '3.5'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    command:
      - 'mongod'
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/